### ISSUE TITLE
Neoforge javadocs planned?

### ISSUE THREAD

**Issue by zsvan** [MCStreetguy/ForgeJavaDocs#1]
Hey! I couldn't find any other way to contact you. Would you be able to include current neoforge javadocs as well?

**Comment by MCStreetguy** [comment]
Hey, I can't guarantee it, but I'll definitely take a look at it. After all, it's a fork of Forge, so the approach I'm using here should certainly be replicable for Neoforge. I'll see if that works in the next few days.

**Comment by zsvan** [comment]
> Hey, I can't guarantee it, but I'll definitely take a look at it. After all, it's a fork of Forge, so the approach I'm using here should certainly be replicable for Neoforge. I'll see if that works in the next few days.

No hurry. Thanks! I frequently use your repo here :P

**Comment by Thunderrock424242** [comment]
any updates on a neoforge doc?

**Comment by MCStreetguy** [comment]
It took me quite a while to get it working, and to be honest it still doesn't for the newer versions of NeoForge, but I decided to 
still publish my current work-in-progress. You can find the new NeoForge JavaDocs project [here (repository)](https://github.com/MCStreetguy/NeoForgeJavaDocs) and [here (GitHub Pages)](https://mcstreetguy.github.io/NeoForgeJavaDocs/). Currently it only contains the versions for 1.20.2, 1.20.3 and 1.20.4 as all releases after that still raise like 100 different errors during the build and I wasn't able to solve these yet, but I'm working on it.
