### ISSUE TITLE
neoforge 1.21?

### ISSUE THREAD

**Issue by Thunderrock424242** [MCStreetguy/ForgeJavaDocs#2]
would be amazing to see neoforge 1.21 on here

**Comment by MCStreetguy** [comment]
Actually I have already been working on generating docs for NeoForge for some time now and just published my current work-in-progress. You can find the new NeoForge JavaDocs project [here (repository)](https://github.com/MCStreetguy/NeoForgeJavaDocs) and [here (GitHub Pages)](https://mcstreetguy.github.io/NeoForgeJavaDocs/). Currently it only contains the versions for 1.20.2, 1.20.3 and 1.20.4 as all releases after that still raise like 100 different errors during the build and I wasn't able to solve these yet. So 1.21 is not yet available there but I'm working on it.
